import type { Patient, OPDVisit, Bill } from '../types';

export function generateSamplePatients(): Patient[] {
  return [
    {
      id: '1',
      patientId: 'P-001',
      name: 'Fatima Rahman',
      age: 28,
      gender: 'female',
      phone: '+880 1712-345678',
      email: 'fatima.rahman@example.com',
      address: 'House 45, Road 12, Dhanmondi, Dhaka 1209',
      bloodGroup: 'A+',
      createdAt: '2026-01-01T10:00:00.000Z',
    },
    {
      id: '2',
      patientId: 'P-002',
      name: 'Ayesha Begum',
      age: 32,
      gender: 'female',
      phone: '+880 1812-456789',
      email: 'ayesha.begum@example.com',
      address: 'Flat 3B, Mohammadpur, Dhaka 1207',
      bloodGroup: 'B+',
      createdAt: '2026-01-02T11:30:00.000Z',
    },
    {
      id: '3',
      patientId: 'P-003',
      name: 'Nusrat Jahan',
      age: 25,
      gender: 'female',
      phone: '+880 1912-567890',
      email: 'nusrat.jahan@example.com',
      address: 'House 78, Gulshan 2, Dhaka 1212',
      bloodGroup: 'O+',
      createdAt: '2026-01-03T09:15:00.000Z',
    },
    {
      id: '4',
      patientId: 'P-004',
      name: 'Sharmin Akter',
      age: 35,
      gender: 'female',
      phone: '+880 1712-678901',
      address: 'Road 27, Banani, Dhaka 1213',
      bloodGroup: 'AB+',
      createdAt: '2026-01-03T14:00:00.000Z',
    },
    {
      id: '5',
      patientId: 'P-005',
      name: 'Tahmina Sultana',
      age: 29,
      gender: 'female',
      phone: '+880 1812-789012',
      email: 'tahmina.sultana@example.com',
      address: 'Block C, Bashundhara R/A, Dhaka 1229',
      bloodGroup: 'A-',
      createdAt: '2026-01-04T10:30:00.000Z',
    },
    {
      id: '6',
      patientId: 'P-006',
      name: 'Razia Khatun',
      age: 31,
      gender: 'female',
      phone: '+880 1912-890123',
      address: 'House 56, Uttara Sector 7, Dhaka 1230',
      bloodGroup: 'O-',
      createdAt: '2026-01-04T15:45:00.000Z',
    },
    {
      id: '7',
      patientId: 'P-007',
      name: 'Nasrin Ahmed',
      age: 27,
      gender: 'female',
      phone: '+880 1712-901234',
      email: 'nasrin.ahmed@example.com',
      address: 'Mirpur DOHS, Dhaka 1216',
      bloodGroup: 'B-',
      createdAt: '2026-01-05T11:00:00.000Z',
    },
    {
      id: '8',
      patientId: 'P-008',
      name: 'Sultana Parvin',
      age: 26,
      gender: 'female',
      phone: '+880 1812-012345',
      address: 'Green Road, Farmgate, Dhaka 1215',
      bloodGroup: 'AB-',
      createdAt: '2026-01-05T16:20:00.000Z',
    },
    {
      id: '9',
      patientId: 'P-009',
      name: 'Rehana Chowdhury',
      age: 33,
      gender: 'female',
      phone: '+880 1912-123456',
      email: 'rehana.chowdhury@example.com',
      address: 'Lalmatia Housing Estate, Dhaka 1207',
      bloodGroup: 'A+',
      createdAt: '2026-01-06T09:30:00.000Z',
    },
    {
      id: '10',
      patientId: 'P-010',
      name: 'Shamima Nasrin',
      age: 30,
      gender: 'female',
      phone: '+880 1712-234567',
      address: 'Shyamoli, Dhaka 1207',
      bloodGroup: 'O+',
      createdAt: '2026-01-06T13:00:00.000Z',
    },
    {
      id: '11',
      patientId: 'P-011',
      name: 'Dilruba Yasmin',
      age: 34,
      gender: 'female',
      phone: '+880 1812-345670',
      email: 'dilruba.yasmin@example.com',
      address: 'Eskaton Garden, Dhaka 1000',
      bloodGroup: 'B+',
      createdAt: '2026-01-07T08:45:00.000Z',
    },
    {
      id: '12',
      patientId: 'P-012',
      name: 'Farhana Islam',
      age: 28,
      gender: 'female',
      phone: '+880 1912-456781',
      address: 'Segunbagicha, Dhaka 1000',
      bloodGroup: 'A-',
      createdAt: '2026-01-07T10:15:00.000Z',
    },
    // General patients (non-gynecology)
    {
      id: '13',
      patientId: 'P-013',
      name: 'Mohammad Karim',
      age: 45,
      gender: 'male',
      phone: '+880 1712-567890',
      email: 'mohammad.karim@example.com',
      address: 'Mirpur 10, Dhaka 1216',
      bloodGroup: 'B+',
      createdAt: '2026-01-05T14:00:00.000Z',
    },
    {
      id: '14',
      patientId: 'P-014',
      name: 'Rafiq Ahmed',
      age: 38,
      gender: 'male',
      phone: '+880 1812-678901',
      address: 'Tejgaon, Dhaka 1215',
      bloodGroup: 'O+',
      createdAt: '2026-01-06T16:30:00.000Z',
    },
    {
      id: '15',
      patientId: 'P-015',
      name: 'Aminul Haque',
      age: 52,
      gender: 'male',
      phone: '+880 1912-789012',
      email: 'aminul.haque@example.com',
      address: 'Motijheel, Dhaka 1000',
      bloodGroup: 'AB+',
      createdAt: '2026-01-04T11:20:00.000Z',
    },
  ];
}

export function generateSampleVisits(): OPDVisit[] {
  return [
    {
      id: 'v1',
      visitId: 'OPD-001',
      patientId: '1',
      patientName: 'Fatima Rahman',
      doctorId: 'd1',
      doctorName: 'Dr. Haiat',
      chiefComplaint: 'Pregnancy checkup - First trimester',
      diagnosis: 'Normal pregnancy progression',
      prescription: 'Folic acid 5mg daily, Calcium supplements, Regular antenatal checkup after 4 weeks',
      visitDate: '2026-01-07T09:00:00.000Z',
      status: 'completed',
      fee: 1000,
    },
    {
      id: 'v2',
      visitId: 'OPD-002',
      patientId: '2',
      patientName: 'Ayesha Begum',
      doctorId: 'd1',
      doctorName: 'Dr. Haiat',
      chiefComplaint: 'Irregular periods and pelvic pain',
      diagnosis: 'Polycystic Ovary Syndrome (PCOS)',
      prescription: 'Metformin 500mg twice daily, Lifestyle modifications, Follow-up in 2 weeks',
      visitDate: '2026-01-07T10:00:00.000Z',
      status: 'completed',
      fee: 800,
    },
    {
      id: 'v3',
      visitId: 'OPD-003',
      patientId: '3',
      patientName: 'Nusrat Jahan',
      doctorId: 'd1',
      doctorName: 'Dr. Haiat',
      chiefComplaint: 'Pre-conception consultation',
      diagnosis: 'Pre-marital counseling and general health assessment',
      prescription: 'Folic acid supplements, Complete blood tests advised',
      visitDate: '2026-01-07T11:00:00.000Z',
      status: 'completed',
      fee: 800,
    },
    {
      id: 'v4',
      visitId: 'OPD-004',
      patientId: '4',
      patientName: 'Sharmin Akter',
      doctorId: 'd1',
      doctorName: 'Dr. Haiat',
      chiefComplaint: 'Heavy menstrual bleeding',
      diagnosis: 'Menorrhagia - further investigation needed',
      prescription: 'Tranexamic acid, Iron supplements, USG pelvis advised',
      visitDate: '2026-01-06T14:30:00.000Z',
      status: 'completed',
      fee: 800,
    },
    {
      id: 'v5',
      visitId: 'OPD-005',
      patientId: '5',
      patientName: 'Tahmina Sultana',
      doctorId: 'd1',
      doctorName: 'Dr. Haiat',
      chiefComplaint: 'Pregnancy checkup - Second trimester',
      diagnosis: 'Normal pregnancy, healthy fetal development',
      prescription: 'Continue prenatal vitamins, Iron supplements, Next visit in 4 weeks',
      visitDate: '2026-01-06T10:00:00.000Z',
      status: 'completed',
      fee: 1000,
    },
    {
      id: 'v6',
      visitId: 'OPD-006',
      patientId: '6',
      patientName: 'Razia Khatun',
      doctorId: 'd1',
      doctorName: 'Dr. Haiat',
      chiefComplaint: 'Lower abdominal pain',
      visitDate: '2026-01-07T14:00:00.000Z',
      status: 'waiting',
      fee: 800,
    },
    {
      id: 'v7',
      visitId: 'OPD-007',
      patientId: '7',
      patientName: 'Nasrin Ahmed',
      doctorId: 'd1',
      doctorName: 'Dr. Haiat',
      chiefComplaint: 'Follow-up visit for UTI',
      diagnosis: 'UTI resolved, good recovery',
      prescription: 'Complete antibiotic course, Increase fluid intake',
      visitDate: '2026-01-05T11:30:00.000Z',
      status: 'completed',
      fee: 500,
    },
    {
      id: 'v8',
      visitId: 'OPD-008',
      patientId: '9',
      patientName: 'Rehana Chowdhury',
      doctorId: 'd1',
      doctorName: 'Dr. Haiat',
      chiefComplaint: 'Annual gynecological checkup',
      diagnosis: 'Normal examination, no abnormalities detected',
      prescription: 'Continue routine health practices, Next checkup in 1 year',
      visitDate: '2026-01-04T09:00:00.000Z',
      status: 'completed',
      fee: 800,
    },
    // General medical consultations (non-gynecology)
    {
      id: 'v9',
      visitId: 'OPD-009',
      patientId: '13',
      patientName: 'Mohammad Karim',
      doctorId: 'd3',
      doctorName: 'Dr. Khan (General Physician)',
      chiefComplaint: 'Fever and body ache for 3 days',
      diagnosis: 'Viral fever',
      prescription: 'Paracetamol 500mg TDS, Rest, Plenty of fluids, Follow-up if fever persists',
      visitDate: '2026-01-06T15:00:00.000Z',
      status: 'completed',
      fee: 500,
    },
    {
      id: 'v10',
      visitId: 'OPD-010',
      patientId: '14',
      patientName: 'Rafiq Ahmed',
      doctorId: 'd3',
      doctorName: 'Dr. Khan (General Physician)',
      chiefComplaint: 'General health checkup and blood test request',
      diagnosis: 'Routine health screening',
      prescription: 'Complete blood count, Lipid profile, Blood sugar tests ordered',
      visitDate: '2026-01-07T12:00:00.000Z',
      status: 'completed',
      fee: 500,
    },
    {
      id: 'v11',
      visitId: 'OPD-011',
      patientId: '15',
      patientName: 'Aminul Haque',
      doctorId: 'd3',
      doctorName: 'Dr. Khan (General Physician)',
      chiefComplaint: 'Chronic cough and chest discomfort',
      visitDate: '2026-01-07T15:30:00.000Z',
      status: 'waiting',
      fee: 500,
    },
  ];
}

export function generateSampleBills(): Bill[] {
  return [
    {
      id: 'b1',
      billNo: 'INV-001',
      patientId: '1',
      patientName: 'Fatima Rahman',
      date: '2026-01-07T09:30:00.000Z',
      items: [
        {
          id: 'i1',
          description: 'OPD Consultation - Antenatal',
          quantity: 1,
          rate: 1000,
          amount: 1000,
        },
        {
          id: 'i2',
          description: 'Ultrasound Scan (Obstetric)',
          quantity: 1,
          rate: 1500,
          amount: 1500,
        },
        {
          id: 'i3',
          description: 'Prenatal Vitamins Pack',
          quantity: 1,
          rate: 500,
          amount: 500,
        },
      ],
      subtotal: 3000,
      discount: 200,
      tax: 0,
      total: 2800,
      paid: 2800,
      balance: 0,
      status: 'paid',
      paymentMethod: 'cash',
    },
    {
      id: 'b2',
      billNo: 'INV-002',
      patientId: '2',
      patientName: 'Ayesha Begum',
      date: '2026-01-07T10:30:00.000Z',
      items: [
        {
          id: 'i4',
          description: 'OPD Consultation',
          quantity: 1,
          rate: 800,
          amount: 800,
        },
        {
          id: 'i5',
          description: 'Hormonal Profile Test',
          quantity: 1,
          rate: 1500,
          amount: 1500,
        },
        {
          id: 'i6',
          description: 'USG Pelvis',
          quantity: 1,
          rate: 1200,
          amount: 1200,
        },
      ],
      subtotal: 3500,
      discount: 0,
      tax: 0,
      total: 3500,
      paid: 2000,
      balance: 1500,
      status: 'partial',
      paymentMethod: 'card',
    },
    {
      id: 'b3',
      billNo: 'INV-003',
      patientId: '3',
      patientName: 'Nusrat Jahan',
      date: '2026-01-07T11:30:00.000Z',
      items: [
        {
          id: 'i7',
          description: 'OPD Consultation - Pre-conception',
          quantity: 1,
          rate: 800,
          amount: 800,
        },
        {
          id: 'i8',
          description: 'Complete Blood Count',
          quantity: 1,
          rate: 600,
          amount: 600,
        },
      ],
      subtotal: 1400,
      discount: 0,
      tax: 0,
      total: 1400,
      paid: 800,
      balance: 600,
      status: 'partial',
      paymentMethod: 'cash',
    },
    {
      id: 'b4',
      billNo: 'INV-004',
      patientId: '4',
      patientName: 'Sharmin Akter',
      date: '2026-01-06T15:00:00.000Z',
      items: [
        {
          id: 'i9',
          description: 'OPD Consultation',
          quantity: 1,
          rate: 800,
          amount: 800,
        },
        {
          id: 'i10',
          description: 'USG Pelvis',
          quantity: 1,
          rate: 1200,
          amount: 1200,
        },
      ],
      subtotal: 2000,
      discount: 0,
      tax: 0,
      total: 2000,
      paid: 0,
      balance: 2000,
      status: 'unpaid',
    },
    {
      id: 'b5',
      billNo: 'INV-005',
      patientId: '5',
      patientName: 'Tahmina Sultana',
      date: '2026-01-06T10:30:00.000Z',
      items: [
        {
          id: 'i11',
          description: 'OPD Consultation - Antenatal',
          quantity: 1,
          rate: 1000,
          amount: 1000,
        },
        {
          id: 'i12',
          description: 'Ultrasound Scan (Obstetric)',
          quantity: 1,
          rate: 1500,
          amount: 1500,
        },
      ],
      subtotal: 2500,
      discount: 0,
      tax: 0,
      total: 2500,
      paid: 2500,
      balance: 0,
      status: 'paid',
      paymentMethod: 'upi',
    },
    {
      id: 'b6',
      billNo: 'INV-006',
      patientId: '7',
      patientName: 'Nasrin Ahmed',
      date: '2026-01-05T12:00:00.000Z',
      items: [
        {
          id: 'i13',
          description: 'OPD Consultation - Follow-up',
          quantity: 1,
          rate: 500,
          amount: 500,
        },
        {
          id: 'i14',
          description: 'Urine Culture Test',
          quantity: 1,
          rate: 800,
          amount: 800,
        },
      ],
      subtotal: 1300,
      discount: 100,
      tax: 0,
      total: 1200,
      paid: 1200,
      balance: 0,
      status: 'paid',
      paymentMethod: 'cash',
    },
    // General medical billing (non-gynecology services)
    {
      id: 'b7',
      billNo: 'INV-007',
      patientId: '14',
      patientName: 'Rafiq Ahmed',
      date: '2026-01-07T12:30:00.000Z',
      items: [
        {
          id: 'i15',
          description: 'OPD Consultation - General',
          quantity: 1,
          rate: 500,
          amount: 500,
        },
        {
          id: 'i16',
          description: 'Complete Blood Count (CBC)',
          quantity: 1,
          rate: 600,
          amount: 600,
        },
        {
          id: 'i17',
          description: 'Lipid Profile Test',
          quantity: 1,
          rate: 900,
          amount: 900,
        },
        {
          id: 'i18',
          description: 'Blood Sugar (Fasting)',
          quantity: 1,
          rate: 300,
          amount: 300,
        },
      ],
      subtotal: 2300,
      discount: 0,
      tax: 0,
      total: 2300,
      paid: 2300,
      balance: 0,
      status: 'paid',
      paymentMethod: 'card',
    },
    {
      id: 'b8',
      billNo: 'INV-008',
      patientId: '13',
      patientName: 'Mohammad Karim',
      date: '2026-01-06T15:30:00.000Z',
      items: [
        {
          id: 'i19',
          description: 'OPD Consultation - General',
          quantity: 1,
          rate: 500,
          amount: 500,
        },
        {
          id: 'i20',
          description: 'Medicines',
          quantity: 1,
          rate: 350,
          amount: 350,
        },
      ],
      subtotal: 850,
      discount: 50,
      tax: 0,
      total: 800,
      paid: 800,
      balance: 0,
      status: 'paid',
      paymentMethod: 'cash',
    },
  ];
}
